#!/bin/sh

git diff --cached --name-only --diff-filter=ACMR -z |
  xargs -0 -r pnpm exec oxfmt --write --no-error-on-unmatched-pattern --
git diff --cached --name-only --diff-filter=ACMR -z | xargs -0 -r git add --
