export const aiPackageRulesCopy = {
  uk: {
    navigationLabel: 'Правила створення пакету',
    navigationDescription: 'Налаштовуйте правила створення пакетів питань.',
    title: 'Правила створення пакету',
    description:
      'Опишіть правила, за якими штучний інтелект має створювати цілі пакети питань.',
    myRules: 'Мої правила створення пакетів',
    add: 'Додати правило',
    empty: 'Ще не додано жодного правила створення пакетів.',
    newRule: 'Нове правило створення пакету',
    editRule: 'Редагування правила створення пакету',
    name: 'Назва правила',
    context: 'Контекст для створення пакету питань',
    contextPlaceholder: 'Тема або задум, що об’єднує всі питання пакету',
    additionalContexts: 'Додатковий контекст для питань',
    addQuestionContext: 'Додати контекст питання',
    questionNumber: 'Номер питання',
    questionType: 'Тип питання',
    questionContext: 'Додатковий контекст',
    save: 'Зберегти',
    saveFailed: 'Не вдалося зберегти правило створення пакету.',
  },
  en: {
    navigationLabel: 'Package-generation rules',
    navigationDescription: 'Configure question-package generation rules.',
    title: 'Package-generation rules',
    description:
      'Describe the rules artificial intelligence should follow when creating complete question packages.',
    myRules: 'My package-generation rules',
    add: 'Add rule',
    empty: 'No package-generation rules have been added yet.',
    newRule: 'New package-generation rule',
    editRule: 'Edit package-generation rule',
    name: 'Rule name',
    context: 'Question-package generation context',
    contextPlaceholder: 'A theme or idea shared by all package questions',
    additionalContexts: 'Additional question context',
    addQuestionContext: 'Add question context',
    questionNumber: 'Question number',
    questionType: 'Question type',
    questionContext: 'Additional context',
    save: 'Save',
    saveFailed: 'Could not save the package-generation rule.',
  },
};
