import { questionGenerationCopy } from './question-generation';

const aiQuestionsCopy = {
  uk: {
    myQuestions: 'Мої види питань',
    globalQuestions: 'Глобальні види питань',
    addGlobal: 'Додати глобальний вид',
    globalEmpty: 'Ще не додано жодного глобального виду питання.',
    title: 'Правила створення питань',
    description:
      'Опишіть види питань, які штучний інтелект має вміти створювати.',
    add: 'Додати мій вид',
    newQuestion: 'Новий вид питання',
    editQuestion: 'Редагування виду питання',
    generalRule: 'Загальне правило для генерації питань',
    name: 'Назва виду питання',
    questionDescription: 'Детальний опис',
    goodExamples: 'Приклади хороших питань',
    badExamples: 'Приклади поганих питань',
    edit: 'Редагувати',
    enable: 'Увімкнути',
    disable: 'Вимкнути',
    favorite: 'Додати до обраного',
    removeFavorite: 'Видалити з обраного',
    delete: 'Видалити',
    deleteConfirmation: (name: string) => `Видалити «${name}»?`,
    save: 'Зберегти',
    saveFailed: 'Не вдалося зберегти вид питання.',
    empty: 'Ще не додано жодного виду питання.',
  },
  en: {
    myQuestions: 'My question kinds',
    globalQuestions: 'Global question kinds',
    addGlobal: 'Add global kind',
    globalEmpty: 'No global question kinds have been added yet.',
    title: 'Question-generation rules',
    description:
      'Describe the kinds of questions that artificial intelligence should be able to create.',
    add: 'Add my kind',
    newQuestion: 'New question kind',
    editQuestion: 'Edit question kind',
    generalRule: 'General rule for question generation',
    name: 'Question kind name',
    questionDescription: 'Detailed description',
    goodExamples: 'Examples of good questions',
    badExamples: 'Examples of bad questions',
    edit: 'Edit',
    enable: 'Enable',
    disable: 'Disable',
    favorite: 'Add to favorites',
    removeFavorite: 'Remove from favorites',
    delete: 'Delete',
    deleteConfirmation: (name: string) => `Delete “${name}”?`,
    save: 'Save',
    saveFailed: 'Could not save the question kind.',
    empty: 'No question kinds have been added yet.',
  },
};

export { aiQuestionsCopy, questionGenerationCopy };
