export type AppLocale = 'uk' | 'en';

const ukrainian = {
  shared: {
    optional: '(необов’язково)',
    remove: 'Видалити',
    chooseFile: 'Вибрати файл',
    or: 'або',
    recentPackages: 'Недавні пакети',
    ready: 'Готовий',
    untitled: 'Без назви',
    question: 'Питання',
    questionNumber: (number: number) => `Питання ${number}`,
    answer: 'Відповідь',
    answerComment: 'Коментар до відповіді',
    handout: 'Роздатка',
    back: 'Назад',
    image: 'Зображення',
    close: 'Закрити',
    zoomOut: 'Зменшити',
    zoomIn: 'Збільшити',
  },
  meta: {
    title: 'Що? Де? Коли?',
    description: 'Інструменти Що? Де? Коли?',
    editorTitle: (fileName?: string | null) =>
      fileName ? `${fileName} — Редактор ЩДК` : 'Що? Де? Коли? — Редактор',
  },
  shell: {
    brand: 'Що? Де? Коли?',
    toolsLabel: 'Інструменти',
    groupLabel: 'ЩДК',
    settingsLabel: 'Налаштування',
    homeTitle: 'Усе для гри в одному місці',
    homeDescription:
      'Створіть пакет запитань у редакторі, а потім відкрийте його в розділі «Провести гру».',
    home: {
      label: 'Домашня',
      description: 'Огляд інструментів для підготовки та проведення гри.',
    },
    host: {
      label: 'Провести гру',
      description: 'Запускайте готовий пакет і проводьте гру для команд.',
    },
    editor: {
      label: 'Редагувати пакети питань',
      description: 'Створюйте та редагуйте пакети запитань у форматі .schdk.',
    },
    visualEditor: {
      label: 'Візуальний редактор',
      description: 'Створюйте власний макет екрана проведення гри.',
    },
  },
  settings: {
    title: 'Налаштування',
    groupsLabel: 'Групи налаштувань',
    appTab: 'Застосунок',
    schdkTab: 'ЩДК',
    languageHeading: 'Мова застосунку',
    languageLabel: 'Мова',
    ukrainian: 'Українська',
    english: 'English',
    themeLabel: 'Тема',
    systemTheme: 'Системна',
    lightTheme: 'Світла',
    darkTheme: 'Темна',
    schdkTabsLabel: 'Налаштування ЩДК',
    gameTab: 'Проведення гри',
    editorTab: 'Редагування питань',
    textCorrection: 'Автоматичне коригування тексту',
    questionText: 'Текст питання',
    sentenceCorrection:
      'Капіталізувати перше слово та додавати крапку, якщо наприкінці немає розділового знака.',
    answers: 'Відповіді',
    answersCorrection:
      'Капіталізувати перше слово основної та альтернативних відповідей.',
    answerComment: 'Коментар до відповіді',
    game: 'Гра',
    signalVolume: 'Гучність звукових сигналів',
    signalVolumeDescription: 'Головний сигнал і попередження таймера.',
  },
  editor: {
    brandEyebrow: 'Редактор пакетів',
    brandTitle: 'Що? Де? Коли?',
    openPackage: 'Відкрийте пакет',
    dropPackage: 'Перетягніть сюди файл .schdk',
    newPackage: 'Новий пакет',
    packageTitle: 'Назва пакета',
    packageTitlePlaceholder: 'Наприклад, Весняна гра 2026',
    packageQuestions: 'Питання пакета',
    round: (number: number) => `Раунд ${number}`,
    copyQuestion: 'Копіювати питання',
    pasteQuestion: 'Вставити питання',
    previousQuestion: 'Попереднє питання',
    nextQuestion: 'Наступне питання',
    questionText: 'Текст питання',
    alternativeAnswers: 'Альтернативні відповіді',
    alternativeAnswer: (number: number) => `Альтернативна відповідь ${number}`,
    addAnswer: 'Додати відповідь',
    hostNotes: 'Примітки для ведучого',
    hostNotesLabel: 'Примітки ведучого',
    questionHandoutAlt: 'Роздатка до питання',
    openHandout: 'Відкрити роздатку у повному розмірі',
    handoutPreview: 'Перегляд роздатки',
    addImage: 'Додати зображення',
    orEnterText: 'Або введіть текст',
    remark: 'Зауваження',
    unresolvedRemark: 'Питання не готове, доки зауваження не вирішено.',
    resolved: 'Вирішено',
    unfinishedGame: 'Незавершена гра',
    filePickerDescription: 'Пакет Що? Де? Коли?',
    saveStatus: {
      saved: 'Файл збережено',
      pending: 'Очікує збереження',
      saving: 'Файл зберігається…',
      error: 'Не вдалося зберегти файл',
    },
    savedDraftRemovalFailed:
      'Файл збережено, але аварійну копію не вдалося видалити.',
    restoreDraft: (fileName: string) =>
      `Знайдено незбережену версію пакета «${fileName}». Відновити її?`,
    draftCheckFailed: 'Не вдалося перевірити аварійну копію в браузері.',
    deepLinkOpenFailed:
      'Не вдалося відкрити пакет із посилання: локальна копія недоступна.',
    restoreFileFailed:
      'Не вдалося відновити попередній файл. Можливо, його переміщено або видалено.',
    draftSaveFailed: 'Не вдалося створити аварійну копію в браузері.',
    autoSaveFailed: 'Не вдалося автоматично зберегти файл.',
    copyFailed:
      'Не вдалося скопіювати питання. Перевірте доступ до буфера обміну.',
    confirmPaste: (number: number) =>
      `Дійсно вставити питання з буфера обміну замість питання ${number}?`,
    pasteFailed:
      'Не вдалося вставити питання. Перевірте доступ до буфера обміну та формат JSON.',
    invalidFile: 'Не вдалося відкрити файл: неправильний формат.',
    recentOpenFailed:
      'Не вдалося відкрити недавній файл. Можливо, його переміщено або видалено.',
    saveFailed: 'Не вдалося зберегти файл.',
  },
  host: {
    eyebrow: 'Проведення гри',
    title: 'Провести гру',
    packageReady: 'Пакет готовий',
    rounds: 'Раундів',
    questions: 'Питань',
    handouts: 'Роздаткових матеріалів',
    hiddenContent:
      'Питання та відповіді залишаються прихованими до початку гри.',
    back: 'Повернутися назад',
    start: 'Почати гру',
    gameProgress: 'Прогрес гри',
    questionIntro: (number: number) => `Питання №${number}`,
    handoutAlt: 'Роздатковий матеріал',
    controls: 'Керування станами питання',
    previousStage: 'Попередній стан',
    nextStage: 'Наступний стан',
    previousStageKeys: '← · PgUp · Backspace',
    nextStageKeys: 'Пробіл · PgDn · →',
    game: 'Проведення гри',
    finished: 'Дякуємо за гру!',
    returnToGames: 'Повернутися до ігор',
    restoreFailed:
      'Не вдалося відновити попередню гру. Можливо, файл переміщено або видалено.',
    invalidFile:
      'Не вдалося відкрити файл: пакет має неправильний формат або ще не готовий до гри.',
    recentOpenFailed:
      'Не вдалося відкрити недавній файл. Можливо, його переміщено, видалено або пакет ще не готовий до гри.',
  },
  visualEditor: {
    labels: {
      logo: 'Лого гри',
      intro: 'Питання №5',
      handout: 'Роздатка',
      question: 'Текст питання',
      timer: 'Таймер',
      answerComment: 'Коментар до відповіді',
      alternativeAnswer: 'Альтернативна відповідь',
      answer: 'Відповідь',
      progress: 'Прогрес',
      controls: 'Кнопки керування',
    },
    previewText: 'Текст питання',
    customText: 'Текст',
    alignments: {
      leftTop: 'Ліворуч угорі',
      centerTop: 'По центру вгорі',
      rightTop: 'Праворуч угорі',
      leftCenter: 'Ліворуч по центру',
      centerCenter: 'По центру',
      rightCenter: 'Праворуч по центру',
      leftBottom: 'Ліворуч унизу',
      centerBottom: 'По центру внизу',
      rightBottom: 'Праворуч унизу',
    },
    customLimit: 'Можна додати не більше 20 власних елементів.',
    imagesTooLarge:
      'Зображення завеликі для збереження. Видаліть одне з них або виберіть менший файл.',
    hiddenSuffix: '. Приховано у грі',
    dragInstruction: 'Перетягніть, щоб змінити позицію',
    textFormatting: 'Оформлення тексту',
    size: 'Розмір',
    color: 'Колір',
    direction: 'Напрямок',
    up: 'Вгору',
    down: 'Вниз',
    fitHeight: 'Підлаштувати до висоти',
    imagePosition: 'Позиція зображення',
    alignment: 'Вирівнювання',
    workspaceActions: 'Дії з робочою областю',
    replaceBackground: 'Замінити фон',
    applyImage: 'Застосувати зображення',
    removeBackground: 'Видалити фон',
    backgroundOpacity: 'Прозорість фону',
    opacity: 'Прозорість',
    actions: (label: string) => `Дії: ${label}`,
    showInGame: 'Показати у грі',
    hideInGame: 'Приховати у грі',
    ownText: 'Власний текст',
    ownImage: 'Власне зображення',
    editText: 'Змінити текст',
    text: 'Текст',
    replaceImage: 'Замінити зображення',
    removeImage: 'Видалити зображення',
    removeElement: 'Видалити елемент',
    addElement: 'Додати елемент',
    addText: 'Додати редагований текст на екран гри',
    addImage: 'Додати власне зображення або логотип',
    importTemplate: 'Імпортувати шаблон оформлення',
    exportTemplate: 'Експортувати шаблон оформлення',
    chooseImage: 'Оберіть файл зображення.',
    gameLayout: 'Макет екрана гри',
    hidden: 'Приховано',
  },
  allWeb: {
    saveVisualsFailed:
      'Не вдалося зберегти оформлення. Видаліть зайві зображення та спробуйте ще раз.',
    importVisualsFailed: 'Не вдалося імпортувати шаблон оформлення.',
    exportVisualsFailed: 'Не вдалося експортувати шаблон оформлення.',
  },
};

const english: typeof ukrainian = {
  shared: {
    optional: '(optional)',
    remove: 'Remove',
    chooseFile: 'Choose file',
    or: 'or',
    recentPackages: 'Recent packages',
    ready: 'Ready',
    untitled: 'Untitled',
    question: 'Question',
    questionNumber: (number) => `Question ${number}`,
    answer: 'Answer',
    answerComment: 'Answer comment',
    handout: 'Handout',
    back: 'Back',
    image: 'Image',
    close: 'Close',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
  },
  meta: {
    title: 'What? Where? When?',
    description: 'What? Where? When? tools',
    editorTitle: (fileName) =>
      fileName ? `${fileName} — WWW Editor` : 'What? Where? When? — Editor',
  },
  shell: {
    brand: 'What? Where? When?',
    toolsLabel: 'Tools',
    groupLabel: 'WWW',
    settingsLabel: 'Settings',
    homeTitle: 'Everything for the game in one place',
    homeDescription:
      'Create a question package in the editor, then open it under “Host a game”.',
    home: {
      label: 'Home',
      description: 'Tools for preparing and hosting a game.',
    },
    host: {
      label: 'Host a game',
      description: 'Open a ready package and host a game for teams.',
    },
    editor: {
      label: 'Edit question packages',
      description: 'Create and edit question packages in the .schdk format.',
    },
    visualEditor: {
      label: 'Visual editor',
      description: 'Create a custom layout for the game screen.',
    },
  },
  settings: {
    title: 'Settings',
    groupsLabel: 'Settings groups',
    appTab: 'App',
    schdkTab: 'WWW',
    languageHeading: 'App language',
    languageLabel: 'Language',
    ukrainian: 'Українська',
    english: 'English',
    themeLabel: 'Theme',
    systemTheme: 'System',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    schdkTabsLabel: 'WWW settings',
    gameTab: 'Hosting',
    editorTab: 'Question editing',
    textCorrection: 'Automatic text correction',
    questionText: 'Question text',
    sentenceCorrection:
      'Capitalize the first word and add a period when no punctuation ends the text.',
    answers: 'Answers',
    answersCorrection:
      'Capitalize the first word of the main and alternative answers.',
    answerComment: 'Answer comment',
    game: 'Game',
    signalVolume: 'Signal volume',
    signalVolumeDescription: 'Main signal and timer warning.',
  },
  editor: {
    brandEyebrow: 'Package editor',
    brandTitle: 'What? Where? When?',
    openPackage: 'Open a package',
    dropPackage: 'Drop a .schdk file here',
    newPackage: 'New package',
    packageTitle: 'Package title',
    packageTitlePlaceholder: 'For example, Spring Game 2026',
    packageQuestions: 'Package questions',
    round: (number) => `Round ${number}`,
    copyQuestion: 'Copy question',
    pasteQuestion: 'Paste question',
    previousQuestion: 'Previous question',
    nextQuestion: 'Next question',
    questionText: 'Question text',
    alternativeAnswers: 'Alternative answers',
    alternativeAnswer: (number) => `Alternative answer ${number}`,
    addAnswer: 'Add answer',
    hostNotes: 'Host notes',
    hostNotesLabel: 'Host notes',
    questionHandoutAlt: 'Question handout',
    openHandout: 'Open handout at full size',
    handoutPreview: 'Handout preview',
    addImage: 'Add image',
    orEnterText: 'Or enter text',
    remark: 'Remark',
    unresolvedRemark: 'The question is not ready until the remark is resolved.',
    resolved: 'Resolved',
    unfinishedGame: 'Unfinished game',
    filePickerDescription: 'What? Where? When? package',
    saveStatus: {
      saved: 'File saved',
      pending: 'Waiting to save',
      saving: 'Saving file…',
      error: 'Could not save file',
    },
    savedDraftRemovalFailed:
      'The file was saved, but its recovery copy could not be removed.',
    restoreDraft: (fileName) =>
      `An unsaved version of “${fileName}” was found. Restore it?`,
    draftCheckFailed: 'Could not check the browser recovery copy.',
    deepLinkOpenFailed:
      'Could not open the linked package because its local copy is unavailable.',
    restoreFileFailed:
      'Could not restore the previous file. It may have been moved or deleted.',
    draftSaveFailed: 'Could not create a browser recovery copy.',
    autoSaveFailed: 'Could not save the file automatically.',
    copyFailed: 'Could not copy the question. Check clipboard access.',
    confirmPaste: (number) =>
      `Replace question ${number} with the question from the clipboard?`,
    pasteFailed:
      'Could not paste the question. Check clipboard access and the JSON format.',
    invalidFile: 'Could not open the file because its format is invalid.',
    recentOpenFailed:
      'Could not open the recent file. It may have been moved or deleted.',
    saveFailed: 'Could not save the file.',
  },
  host: {
    eyebrow: 'Game hosting',
    title: 'Host a game',
    packageReady: 'Package ready',
    rounds: 'Rounds',
    questions: 'Questions',
    handouts: 'Handouts',
    hiddenContent: 'Questions and answers stay hidden until the game begins.',
    back: 'Go back',
    start: 'Start game',
    gameProgress: 'Game progress',
    questionIntro: (number) => `Question #${number}`,
    handoutAlt: 'Handout material',
    controls: 'Question stage controls',
    previousStage: 'Previous stage',
    nextStage: 'Next stage',
    previousStageKeys: '← · PgUp · Backspace',
    nextStageKeys: 'Space · PgDn · →',
    game: 'Game hosting',
    finished: 'Thank you for playing!',
    returnToGames: 'Return to games',
    restoreFailed:
      'Could not restore the previous game. The file may have been moved or deleted.',
    invalidFile:
      'Could not open the file because the package is invalid or not ready to play.',
    recentOpenFailed:
      'Could not open the recent file. It may have been moved, deleted, or may not be ready to play.',
  },
  visualEditor: {
    labels: {
      logo: 'Game logo',
      intro: 'Question #5',
      handout: 'Handout',
      question: 'Question text',
      timer: 'Timer',
      answerComment: 'Answer comment',
      alternativeAnswer: 'Alternative answer',
      answer: 'Answer',
      progress: 'Progress',
      controls: 'Controls',
    },
    previewText: 'Question text',
    customText: 'Text',
    alignments: {
      leftTop: 'Top left',
      centerTop: 'Top center',
      rightTop: 'Top right',
      leftCenter: 'Center left',
      centerCenter: 'Center',
      rightCenter: 'Center right',
      leftBottom: 'Bottom left',
      centerBottom: 'Bottom center',
      rightBottom: 'Bottom right',
    },
    customLimit: 'You can add up to 20 custom elements.',
    imagesTooLarge:
      'The images are too large to save. Remove one or choose a smaller file.',
    hiddenSuffix: '. Hidden in game',
    dragInstruction: 'Drag to change position',
    textFormatting: 'Text formatting',
    size: 'Size',
    color: 'Color',
    direction: 'Direction',
    up: 'Up',
    down: 'Down',
    fitHeight: 'Fit to height',
    imagePosition: 'Image position',
    alignment: 'Alignment',
    workspaceActions: 'Workspace actions',
    replaceBackground: 'Replace background',
    applyImage: 'Apply image',
    removeBackground: 'Remove background',
    backgroundOpacity: 'Background opacity',
    opacity: 'Opacity',
    actions: (label) => `Actions: ${label}`,
    showInGame: 'Show in game',
    hideInGame: 'Hide in game',
    ownText: 'Custom text',
    ownImage: 'Custom image',
    editText: 'Edit text',
    text: 'Text',
    replaceImage: 'Replace image',
    removeImage: 'Remove image',
    removeElement: 'Remove element',
    addElement: 'Add element',
    addText: 'Add editable text to the game screen',
    addImage: 'Add a custom image or logo',
    importTemplate: 'Import layout template',
    exportTemplate: 'Export layout template',
    chooseImage: 'Choose an image file.',
    gameLayout: 'Game screen layout',
    hidden: 'Hidden',
  },
  allWeb: {
    saveVisualsFailed:
      'Could not save the layout. Remove extra images and try again.',
    importVisualsFailed: 'Could not import the layout template.',
    exportVisualsFailed: 'Could not export the layout template.',
  },
};

export type LocalizationCopy = typeof ukrainian;

export const LOCALIZATION_COPY: Record<AppLocale, LocalizationCopy> = {
  uk: ukrainian,
  en: english,
};
