export const editorCopy = {
  uk: {
    brandEyebrow: 'Редактор пакетів',
    brandTitle: 'Що? Де? Коли?',
    openPackage: 'Відкрийте пакет',
    dropPackage: 'Перетягніть сюди файл .schdk',
    newPackage: 'Новий пакет',
    packageTitle: 'Назва пакета',
    packageTitlePlaceholder: 'Наприклад, Весняна гра 2026',
    packageQuestions: 'Питання пакета',
    tour: (number: number) => `Тур ${number}`,
    tourPhrase: 'Фраза туру',
    musicBreak: 'Музична пауза',
    noMusic: 'Музику не додано',
    addMusic: 'Додати музику',
    replaceMusic: 'Замінити музику',
    invalidMusic: 'Цей аудіофайл не підтримується вбудованим програвачем.',
    copyQuestion: 'Копіювати питання',
    pasteQuestion: 'Вставити питання',
    questionType: 'Тип питання',
    questionTypes: {
      standard: 'Звичайне',
      blitz2x30: 'Бліц 2×30',
      blitz3x20: 'Бліц 3×20',
    },
    questionText: 'Текст питання',
    questionPart: (number: number) => `Частина питання ${number}`,
    alternativeAnswers: 'Альтернативні відповіді',
    alternativeAnswer: (number: number) => `Альтернативна відповідь ${number}`,
    wrongAnswers: 'Неправильні відповіді',
    wrongAnswer: (number: number) => `Неправильна відповідь ${number}`,
    addAnswer: 'Додати відповідь',
    hostNotes: 'Примітки для ведучого',
    hostNotesLabel: 'Примітки ведучого',
    questionHandoutAlt: 'Роздатка до питання',
    openHandout: 'Відкрити роздатку у повному розмірі',
    handoutPreview: 'Перегляд роздатки',
    addImage: 'Додати зображення додатки',
    orEnterText: 'Додати текст додатки',
    remark: 'Зауваження',
    unresolvedRemark: 'Питання не готове, доки зауваження не вирішено.',
    resolved: 'Вирішено',
    unfinishedGame: 'Незавершена гра',
    filePickerDescription: 'Пакет Що? Де? Коли?',
    saveStatus: {
      saved: 'Файл збережено',
      pending: 'Очікує збереження',
      saving: 'Файл зберігається…',
      error: 'Не вдалося зберегти файл',
    },
    savedDraftRemovalFailed:
      'Файл збережено, але аварійну копію не вдалося видалити.',
    restoreDraft: (fileName: string) =>
      `Знайдено незбережену версію пакета «${fileName}». Відновити її?`,
    draftCheckFailed: 'Не вдалося перевірити аварійну копію в браузері.',
    deepLinkOpenFailed:
      'Не вдалося відкрити пакет із посилання: локальна копія недоступна.',
    restoreFileFailed:
      'Не вдалося відновити попередній файл. Можливо, його переміщено або видалено.',
    draftSaveFailed: 'Не вдалося створити аварійну копію в браузері.',
    autoSaveFailed: 'Не вдалося автоматично зберегти файл.',
    driveConflict:
      'Цей пакет змінено в Google Диску. Зберегти ваші зміни як нову копію та відкрити новішу версію?',
    resolveDriveConflict: 'Зберегти копію та відкрити',
    conflictCopyTitle: (title: string) => `${title} — конфліктна копія`,
    copyFailed:
      'Не вдалося скопіювати питання. Перевірте доступ до буфера обміну.',
    confirmPaste: (number: number) =>
      `Дійсно вставити питання з буфера обміну замість питання ${number}?`,
    pasteFailed:
      'Не вдалося вставити питання. Перевірте доступ до буфера обміну та формат JSON.',
    invalidFile: 'Не вдалося відкрити файл: неправильний формат.',
    recentOpenFailed:
      'Не вдалося відкрити недавній файл. Можливо, його переміщено або видалено.',
    downloadFailed: 'Не вдалося завантажити файл із Google Диска.',
    saveFailed: 'Не вдалося зберегти файл.',
  },
  en: {
    brandEyebrow: 'Package editor',
    brandTitle: 'What? Where? When?',
    openPackage: 'Open a package',
    dropPackage: 'Drop a .schdk file here',
    newPackage: 'New package',
    packageTitle: 'Package title',
    packageTitlePlaceholder: 'For example, Spring Game 2026',
    packageQuestions: 'Package questions',
    tour: (number: number) => `Tour ${number}`,
    tourPhrase: 'Tour phrase',
    musicBreak: 'Music break',
    noMusic: 'No music added',
    addMusic: 'Add music',
    replaceMusic: 'Replace music',
    invalidMusic: 'The built-in player does not support this audio file.',
    copyQuestion: 'Copy question',
    pasteQuestion: 'Paste question',
    questionType: 'Question type',
    questionTypes: {
      standard: 'Standard',
      blitz2x30: 'Blitz 2×30',
      blitz3x20: 'Blitz 3×20',
    },
    questionText: 'Question text',
    questionPart: (number: number) => `Question part ${number}`,
    alternativeAnswers: 'Alternative answers',
    alternativeAnswer: (number: number) => `Alternative answer ${number}`,
    wrongAnswers: 'Wrong answers',
    wrongAnswer: (number: number) => `Wrong answer ${number}`,
    addAnswer: 'Add answer',
    hostNotes: 'Host notes',
    hostNotesLabel: 'Host notes',
    questionHandoutAlt: 'Question handout',
    openHandout: 'Open handout at full size',
    handoutPreview: 'Handout preview',
    addImage: 'Add handout image',
    orEnterText: 'Add handout text',
    remark: 'Remark',
    unresolvedRemark: 'The question is not ready until the remark is resolved.',
    resolved: 'Resolved',
    unfinishedGame: 'Unfinished game',
    filePickerDescription: 'What? Where? When? package',
    saveStatus: {
      saved: 'File saved',
      pending: 'Waiting to save',
      saving: 'Saving file…',
      error: 'Could not save file',
    },
    savedDraftRemovalFailed:
      'The file was saved, but its recovery copy could not be removed.',
    restoreDraft: (fileName: string) =>
      `An unsaved version of “${fileName}” was found. Restore it?`,
    draftCheckFailed: 'Could not check the browser recovery copy.',
    deepLinkOpenFailed:
      'Could not open the linked package because its local copy is unavailable.',
    restoreFileFailed:
      'Could not restore the previous file. It may have been moved or deleted.',
    draftSaveFailed: 'Could not create a browser recovery copy.',
    autoSaveFailed: 'Could not save the file automatically.',
    driveConflict:
      'This package changed in Google Drive. Save your edits as a new copy and open the newer version?',
    resolveDriveConflict: 'Save copy and open',
    conflictCopyTitle: (title: string) => `${title} — conflict copy`,
    copyFailed: 'Could not copy the question. Check clipboard access.',
    confirmPaste: (number: number) =>
      `Replace question ${number} with the question from the clipboard?`,
    pasteFailed:
      'Could not paste the question. Check clipboard access and the JSON format.',
    invalidFile: 'Could not open the file because its format is invalid.',
    recentOpenFailed:
      'Could not open the recent file. It may have been moved or deleted.',
    downloadFailed: 'Could not download the file from Google Drive.',
    saveFailed: 'Could not save the file.',
  },
};
