import { ukrainian } from './ukrainian';
import { englishSettings } from './english-settings';
import { aiQuestionsCopy, questionGenerationCopy } from './ai-questions';
export const english: typeof ukrainian = {
  shared: {
    confirmation: 'Confirm action',
    confirm: 'Confirm',
    cancel: 'Cancel',
    optional: '(optional)',
    remove: 'Remove',
    chooseFile: 'Choose file',
    or: 'or',
    recentPackages: 'Recent packages',
    downloadPackage: 'Download package',
    deletePackage: 'Delete package from the cloud',
    deletePackageConfirmation: (name) =>
      `Move “${name}” to Google Drive trash?`,
    deletePackageFailed: 'Could not delete the package from Google Drive.',
    ready: 'Ready',
    untitled: 'Untitled',
    question: 'Question',
    questionNumber: (number) => `Question ${number}`,
    answer: 'Answer',
    answerComment: 'Answer comment',
    handout: 'Handout',
    back: 'Back',
    image: 'Image',
    close: 'Close',
    zoomOut: 'Zoom out',
    zoomIn: 'Zoom in',
  },
  meta: {
    title: 'What? Where? When?',
    description: 'What? Where? When? tools',
    editorTitle: (fileName) =>
      fileName ? `${fileName} — WWW Editor` : 'What? Where? When? — Editor',
  },
  shell: {
    brand: 'What? Where? When?',
    toolsLabel: 'Tools',
    groupLabel: 'WWW',
    settingsLabel: 'Settings',
    accountConnected: 'Connected',
    accountDisconnected: 'Disconnected',
    loginTitle: 'Sign in with Google',
    loginDescription:
      'Sign in to create, open, and save SCHDK packages in Google Drive.',
    loginAction: 'Continue with Google',
    homeTitle: 'Everything for the game in one place',
    homeDescription:
      'Set up the layout in the visual editor, then create a question package, then start the game.',
    home: {
      label: 'Home',
      description: 'Tools for preparing and hosting a game.',
    },
    host: {
      label: 'Host a game',
      description: 'Open a ready package and host a game for teams.',
    },
    editor: {
      label: 'Edit question packages',
      description: 'Create and edit question packages in the .schdk format.',
    },
    visualEditor: {
      label: 'Visual editor',
      description: 'Create a custom layout for the game screen.',
    },
    artificialIntelligence: {
      label: 'Artificial intelligence',
      description: 'Configure question-generation rules.',
    },
  },
  aiQuestions: aiQuestionsCopy.en,
  questionGeneration: questionGenerationCopy.en,
  settings: englishSettings,
  editor: {
    brandEyebrow: 'Package editor',
    brandTitle: 'What? Where? When?',
    openPackage: 'Open a package',
    dropPackage: 'Drop a .schdk file here',
    newPackage: 'New package',
    packageTitle: 'Package title',
    packageTitlePlaceholder: 'For example, Spring Game 2026',
    packageQuestions: 'Package questions',
    round: (number) => `Round ${number}`,
    musicBreak: 'Music break',
    noMusic: 'No music added',
    addMusic: 'Add music',
    replaceMusic: 'Replace music',
    invalidMusic: 'The built-in player does not support this audio file.',
    copyQuestion: 'Copy question',
    pasteQuestion: 'Paste question',
    previousQuestion: 'Previous question',
    nextQuestion: 'Next question',
    questionType: 'Question type',
    questionTypes: {
      standard: 'Standard',
      blitz2x30: 'Blitz 2×30',
      blitz3x20: 'Blitz 3×20',
    },
    questionText: 'Question text',
    questionPart: (number) => `Question part ${number}`,
    alternativeAnswers: 'Alternative answers',
    alternativeAnswer: (number) => `Alternative answer ${number}`,
    wrongAnswers: 'Wrong answers',
    wrongAnswer: (number) => `Wrong answer ${number}`,
    addAnswer: 'Add answer',
    hostNotes: 'Host notes',
    hostNotesLabel: 'Host notes',
    questionHandoutAlt: 'Question handout',
    openHandout: 'Open handout at full size',
    handoutPreview: 'Handout preview',
    addImage: 'Add image',
    orEnterText: 'Or enter text',
    remark: 'Remark',
    unresolvedRemark: 'The question is not ready until the remark is resolved.',
    resolved: 'Resolved',
    unfinishedGame: 'Unfinished game',
    filePickerDescription: 'What? Where? When? package',
    saveStatus: {
      saved: 'File saved',
      pending: 'Waiting to save',
      saving: 'Saving file…',
      error: 'Could not save file',
    },
    savedDraftRemovalFailed:
      'The file was saved, but its recovery copy could not be removed.',
    restoreDraft: (fileName) =>
      `An unsaved version of “${fileName}” was found. Restore it?`,
    draftCheckFailed: 'Could not check the browser recovery copy.',
    deepLinkOpenFailed:
      'Could not open the linked package because its local copy is unavailable.',
    restoreFileFailed:
      'Could not restore the previous file. It may have been moved or deleted.',
    draftSaveFailed: 'Could not create a browser recovery copy.',
    autoSaveFailed: 'Could not save the file automatically.',
    copyFailed: 'Could not copy the question. Check clipboard access.',
    confirmPaste: (number) =>
      `Replace question ${number} with the question from the clipboard?`,
    pasteFailed:
      'Could not paste the question. Check clipboard access and the JSON format.',
    invalidFile: 'Could not open the file because its format is invalid.',
    recentOpenFailed:
      'Could not open the recent file. It may have been moved or deleted.',
    downloadFailed: 'Could not download the file from Google Drive.',
    saveFailed: 'Could not save the file.',
  },
  host: {
    eyebrow: 'Game hosting',
    title: 'Host a game',
    packageReady: 'Package ready',
    rounds: 'Rounds',
    questions: 'Questions',
    handouts: 'Handouts',
    hiddenContent: 'Questions and answers stay hidden until the game begins.',
    back: 'Go back',
    start: 'Start game',
    gameProgress: 'Game progress',
    questionIntro: (number) => `Question #${number}`,
    musicBreak: 'Music break',
    handoutAlt: 'Handout material',
    controls: 'Question stage controls',
    previousStage: 'Previous stage',
    nextStage: 'Next stage',
    previousStageKeys: '← · PgUp · Backspace',
    nextStageKeys: 'Space · PgDn · →',
    game: 'Game hosting',
    finished: 'Thank you for playing!',
    returnToGames: 'Return to games',
    exitGameConfirmation:
      'Exit the game? The current hosting progress will be reset.',
    restoreFailed:
      'Could not restore the previous game. The file may have been moved or deleted.',
    invalidFile:
      'Could not open the file because the package is invalid or not ready to play.',
    uploadFailed: 'Could not upload the file to Google Drive.',
    downloadFailed: 'Could not download the file from Google Drive.',
    recentOpenFailed:
      'Could not open the recent file. It may have been moved, deleted, or may not be ready to play.',
  },
  visualEditor: {
    labels: {
      logo: 'Game logo',
      intro: 'Question #5',
      handout: 'Handout',
      question: 'Question text',
      timer: 'Timer',
      answerComment: 'Answer comment',
      alternativeAnswer: 'Alternative answer',
      answer: 'Answer',
      progress: 'Progress',
      controls: 'Controls',
    },
    previewText: 'Question text',
    customText: 'Text',
    alignments: {
      leftTop: 'Top left',
      centerTop: 'Top center',
      rightTop: 'Top right',
      leftCenter: 'Center left',
      centerCenter: 'Center',
      rightCenter: 'Center right',
      leftBottom: 'Bottom left',
      centerBottom: 'Bottom center',
      rightBottom: 'Bottom right',
    },
    customLimit: 'You can add up to 20 custom elements.',
    imagesTooLarge:
      'The images are too large to save. Remove one or choose a smaller file.',
    hiddenSuffix: '. Hidden in game',
    dragInstruction: 'Drag to change position',
    textFormatting: 'Text formatting',
    size: 'Size',
    color: 'Color',
    direction: 'Direction',
    up: 'Up',
    down: 'Down',
    fitHeight: 'Fit to height',
    fitWarning: 'Enlarge the element or shorten the text',
    imagePosition: 'Image position',
    alignment: 'Alignment',
    workspaceActions: 'Workspace actions',
    replaceBackground: 'Replace background',
    applyImage: 'Apply image',
    removeBackground: 'Remove background',
    backgroundOpacity: 'Background opacity',
    opacity: 'Opacity',
    actions: (label) => `Actions: ${label}`,
    showInGame: 'Show in game',
    hideInGame: 'Hide in game',
    ownText: 'Custom text',
    ownImage: 'Custom image',
    editText: 'Edit text',
    text: 'Text',
    replaceImage: 'Replace image',
    removeImage: 'Remove image',
    removeElement: 'Remove element',
    addElement: 'Add element',
    addText: 'Add editable text to the game screen',
    addImage: 'Add a custom image or logo',
    importTemplate: 'Import layout template',
    exportTemplate: 'Export layout template',
    chooseImage: 'Choose an image file.',
    gameLayout: 'Game screen layout',
    hidden: 'Hidden',
  },
  allWeb: {
    saveVisualsFailed:
      'Could not save the layout. Remove extra images and try again.',
    importVisualsFailed: 'Could not import the layout template.',
    exportVisualsFailed: 'Could not export the layout template.',
  },
};
