export type AppLocale = 'uk' | 'en';

import { ukrainianSettings } from './ukrainian-settings';

export const ukrainian = {
  shared: {
    optional: '(необов’язково)',
    remove: 'Видалити',
    chooseFile: 'Вибрати файл',
    or: 'або',
    recentPackages: 'Недавні пакети',
    ready: 'Готовий',
    untitled: 'Без назви',
    question: 'Питання',
    questionNumber: (number: number) => `Питання ${number}`,
    answer: 'Відповідь',
    answerComment: 'Коментар до відповіді',
    handout: 'Роздатка',
    back: 'Назад',
    image: 'Зображення',
    close: 'Закрити',
    zoomOut: 'Зменшити',
    zoomIn: 'Збільшити',
  },
  meta: {
    title: 'Що? Де? Коли?',
    description: 'Інструменти Що? Де? Коли?',
    editorTitle: (fileName?: string | null) =>
      fileName ? `${fileName} — Редактор ЩДК` : 'Що? Де? Коли? — Редактор',
  },
  shell: {
    brand: 'Що? Де? Коли?',
    toolsLabel: 'Інструменти',
    groupLabel: 'ЩДК',
    settingsLabel: 'Налаштування',
    accountConnected: 'Підключено',
    accountDisconnected: 'Не підключено',
    homeTitle: 'Усе для гри в одному місці',
    homeDescription:
      'Створіть пакет запитань у редакторі, а потім відкрийте його в розділі «Провести гру».',
    home: {
      label: 'Домашня',
      description: 'Огляд інструментів для підготовки та проведення гри.',
    },
    host: {
      label: 'Провести гру',
      description: 'Запускайте готовий пакет і проводьте гру для команд.',
    },
    editor: {
      label: 'Редагувати пакети питань',
      description: 'Створюйте та редагуйте пакети запитань у форматі .schdk.',
    },
    visualEditor: {
      label: 'Візуальний редактор',
      description: 'Створюйте власний макет екрана проведення гри.',
    },
  },
  settings: ukrainianSettings,
  editor: {
    brandEyebrow: 'Редактор пакетів',
    brandTitle: 'Що? Де? Коли?',
    openPackage: 'Відкрийте пакет',
    dropPackage: 'Перетягніть сюди файл .schdk',
    newPackage: 'Новий пакет',
    packageTitle: 'Назва пакета',
    packageTitlePlaceholder: 'Наприклад, Весняна гра 2026',
    packageQuestions: 'Питання пакета',
    round: (number: number) => `Раунд ${number}`,
    copyQuestion: 'Копіювати питання',
    pasteQuestion: 'Вставити питання',
    previousQuestion: 'Попереднє питання',
    nextQuestion: 'Наступне питання',
    questionType: 'Тип питання',
    questionTypes: {
      standard: 'Звичайне',
      blitz2x30: 'Бліц 2×30',
      blitz3x20: 'Бліц 3×20',
    },
    questionText: 'Текст питання',
    questionPart: (number: number) => `Частина питання ${number}`,
    alternativeAnswers: 'Альтернативні відповіді',
    alternativeAnswer: (number: number) => `Альтернативна відповідь ${number}`,
    wrongAnswers: 'Неправильні відповіді',
    wrongAnswer: (number: number) => `Неправильна відповідь ${number}`,
    addAnswer: 'Додати відповідь',
    hostNotes: 'Примітки для ведучого',
    hostNotesLabel: 'Примітки ведучого',
    questionHandoutAlt: 'Роздатка до питання',
    openHandout: 'Відкрити роздатку у повному розмірі',
    handoutPreview: 'Перегляд роздатки',
    addImage: 'Додати зображення',
    orEnterText: 'Або введіть текст',
    remark: 'Зауваження',
    unresolvedRemark: 'Питання не готове, доки зауваження не вирішено.',
    resolved: 'Вирішено',
    unfinishedGame: 'Незавершена гра',
    filePickerDescription: 'Пакет Що? Де? Коли?',
    saveStatus: {
      saved: 'Файл збережено',
      pending: 'Очікує збереження',
      saving: 'Файл зберігається…',
      error: 'Не вдалося зберегти файл',
    },
    savedDraftRemovalFailed:
      'Файл збережено, але аварійну копію не вдалося видалити.',
    restoreDraft: (fileName: string) =>
      `Знайдено незбережену версію пакета «${fileName}». Відновити її?`,
    draftCheckFailed: 'Не вдалося перевірити аварійну копію в браузері.',
    deepLinkOpenFailed:
      'Не вдалося відкрити пакет із посилання: локальна копія недоступна.',
    restoreFileFailed:
      'Не вдалося відновити попередній файл. Можливо, його переміщено або видалено.',
    draftSaveFailed: 'Не вдалося створити аварійну копію в браузері.',
    autoSaveFailed: 'Не вдалося автоматично зберегти файл.',
    copyFailed:
      'Не вдалося скопіювати питання. Перевірте доступ до буфера обміну.',
    confirmPaste: (number: number) =>
      `Дійсно вставити питання з буфера обміну замість питання ${number}?`,
    pasteFailed:
      'Не вдалося вставити питання. Перевірте доступ до буфера обміну та формат JSON.',
    invalidFile: 'Не вдалося відкрити файл: неправильний формат.',
    recentOpenFailed:
      'Не вдалося відкрити недавній файл. Можливо, його переміщено або видалено.',
    saveFailed: 'Не вдалося зберегти файл.',
  },
  host: {
    eyebrow: 'Проведення гри',
    title: 'Провести гру',
    packageReady: 'Пакет готовий',
    rounds: 'Раундів',
    questions: 'Питань',
    handouts: 'Роздаткових матеріалів',
    hiddenContent:
      'Питання та відповіді залишаються прихованими до початку гри.',
    back: 'Повернутися назад',
    start: 'Почати гру',
    gameProgress: 'Прогрес гри',
    questionIntro: (number: number) => `Питання №${number}`,
    handoutAlt: 'Роздатковий матеріал',
    controls: 'Керування станами питання',
    previousStage: 'Попередній стан',
    nextStage: 'Наступний стан',
    previousStageKeys: '← · PgUp · Backspace',
    nextStageKeys: 'Пробіл · PgDn · →',
    game: 'Проведення гри',
    finished: 'Дякуємо за гру!',
    returnToGames: 'Повернутися до ігор',
    restoreFailed:
      'Не вдалося відновити попередню гру. Можливо, файл переміщено або видалено.',
    invalidFile:
      'Не вдалося відкрити файл: пакет має неправильний формат або ще не готовий до гри.',
    recentOpenFailed:
      'Не вдалося відкрити недавній файл. Можливо, його переміщено, видалено або пакет ще не готовий до гри.',
  },
  visualEditor: {
    labels: {
      logo: 'Лого гри',
      intro: 'Питання №5',
      handout: 'Роздатка',
      question: 'Текст питання',
      timer: 'Таймер',
      answerComment: 'Коментар до відповіді',
      alternativeAnswer: 'Альтернативна відповідь',
      answer: 'Відповідь',
      progress: 'Прогрес',
      controls: 'Кнопки керування',
    },
    previewText: 'Текст питання',
    customText: 'Текст',
    alignments: {
      leftTop: 'Ліворуч угорі',
      centerTop: 'По центру вгорі',
      rightTop: 'Праворуч угорі',
      leftCenter: 'Ліворуч по центру',
      centerCenter: 'По центру',
      rightCenter: 'Праворуч по центру',
      leftBottom: 'Ліворуч унизу',
      centerBottom: 'По центру внизу',
      rightBottom: 'Праворуч унизу',
    },
    customLimit: 'Можна додати не більше 20 власних елементів.',
    imagesTooLarge:
      'Зображення завеликі для збереження. Видаліть одне з них або виберіть менший файл.',
    hiddenSuffix: '. Приховано у грі',
    dragInstruction: 'Перетягніть, щоб змінити позицію',
    textFormatting: 'Оформлення тексту',
    size: 'Розмір',
    color: 'Колір',
    direction: 'Напрямок',
    up: 'Вгору',
    down: 'Вниз',
    fitHeight: 'Підлаштувати до висоти',
    imagePosition: 'Позиція зображення',
    alignment: 'Вирівнювання',
    workspaceActions: 'Дії з робочою областю',
    replaceBackground: 'Замінити фон',
    applyImage: 'Застосувати зображення',
    removeBackground: 'Видалити фон',
    backgroundOpacity: 'Прозорість фону',
    opacity: 'Прозорість',
    actions: (label: string) => `Дії: ${label}`,
    showInGame: 'Показати у грі',
    hideInGame: 'Приховати у грі',
    ownText: 'Власний текст',
    ownImage: 'Власне зображення',
    editText: 'Змінити текст',
    text: 'Текст',
    replaceImage: 'Замінити зображення',
    removeImage: 'Видалити зображення',
    removeElement: 'Видалити елемент',
    addElement: 'Додати елемент',
    addText: 'Додати редагований текст на екран гри',
    addImage: 'Додати власне зображення або логотип',
    importTemplate: 'Імпортувати шаблон оформлення',
    exportTemplate: 'Експортувати шаблон оформлення',
    chooseImage: 'Оберіть файл зображення.',
    gameLayout: 'Макет екрана гри',
    hidden: 'Приховано',
  },
  allWeb: {
    saveVisualsFailed:
      'Не вдалося зберегти оформлення. Видаліть зайві зображення та спробуйте ще раз.',
    importVisualsFailed: 'Не вдалося імпортувати шаблон оформлення.',
    exportVisualsFailed: 'Не вдалося експортувати шаблон оформлення.',
  },
};
