export const ukrainianSettings = {
  title: 'Налаштування',
  groupsLabel: 'Групи налаштувань',
  appTab: 'Застосунок',
  schdkTab: 'ЩДК',
  languageHeading: 'Мова застосунку',
  languageLabel: 'Мова',
  ukrainian: 'Українська',
  english: 'English',
  themeLabel: 'Тема',
  systemTheme: 'Системна',
  lightTheme: 'Світла',
  darkTheme: 'Темна',
  googleDriveHeading: 'Google Диск',
  googleDriveUnavailable: 'Додайте OAuth client ID до конфігурації застосунку.',
  googleDriveDisconnected: 'Не підключено.',
  googleDriveConnecting: 'Підключення…',
  googleDriveConnected: (account: string) =>
    account ? `Підключено: ${account}` : 'Підключено.',
  googleDriveReconnect: 'Потрібно повторно надати доступ.',
  googleDriveError: 'Не вдалося синхронізувати налаштування.',
  googleDriveConnect: 'Підключити',
  googleDriveReconnectAction: 'Підключити знову',
  googleDriveDisconnect: 'Відключити',
  schdkTabsLabel: 'Налаштування ЩДК',
  gameTab: 'Проведення гри',
  editorTab: 'Редагування питань',
  textCorrection: 'Автоматичне коригування тексту',
  questionText: 'Текст питання',
  sentenceCorrection:
    'Капіталізувати перше слово та додавати крапку, якщо наприкінці немає розділового знака.',
  answers: 'Відповіді',
  answersCorrection:
    'Капіталізувати перше слово основної, альтернативних і неправильних відповідей.',
  answerComment: 'Коментар до відповіді',
  game: 'Гра',
  signalVolume: 'Гучність звукових сигналів',
  signalVolumeDescription: 'Головний сигнал і попередження таймера.',
};
