export const ukrainianSettings = {
  title: 'Налаштування',
  groupsLabel: 'Групи налаштувань',
  appTab: 'Застосунок',
  schdkTab: 'ЩДК',
  artificialIntelligenceTab: 'Штучний інтелект',
  languageLabel: 'Мова',
  ukrainian: 'Українська',
  english: 'English',
  themeLabel: 'Тема',
  systemTheme: 'Системна',
  lightTheme: 'Світла',
  darkTheme: 'Темна',
  googleDriveHeading: 'Google Диск',
  googleDriveUnavailable: 'Додайте OAuth client ID до конфігурації застосунку.',
  googleDriveDisconnected: 'Не підключено.',
  googleDriveConnecting: 'Підключення…',
  googleDriveConnected: (account: string) =>
    account ? `Підключено: ${account}` : 'Підключено.',
  googleDriveReconnect: 'Потрібно повторно надати доступ.',
  googleDriveError: 'Не вдалося синхронізувати налаштування.',
  googleDriveConnect: 'Підключити',
  googleDriveReconnectAction: 'Підключити знову',
  googleDriveDisconnect: 'Відключити',
  aiProviderModel: 'Провайдер і модель ШІ',
  aiProviderModelDescription:
    'Оберіть сервіс штучного інтелекту та модель для генерації запитань.',
  aiProvider: 'Провайдер',
  aiModel: 'Модель',
  aiApiKey: 'API-ключ',
  aiApiKeyDescription:
    'У браузері ключ зберігається до закриття вкладки; у настільному застосунку — у зашифрованому сховищі операційної системи.',
  aiApiKeyPlaceholder: 'Вставте API-ключ',
  aiApiKeyConfigured: 'API-ключ збережено.',
  aiApiKeyMissing: 'API-ключ не збережено.',
  aiApiKeySave: 'Зберегти',
  aiApiKeyRemove: 'Видалити',
  aiApiKeySaveFailed: 'Не вдалося зберегти API-ключ.',
  shortcutsTitle: 'Гарячі клавіші',
  shortcutGroups: [
    {
      heading: 'Проведення гри',
      items: [
        { label: 'Наступний стан', keys: 'Пробіл · PgDn · →' },
        { label: 'Попередній стан', keys: 'Backspace · PgUp · ←' },
        { label: 'Вийти з гри', keys: 'Alt + Q' },
      ],
    },
    {
      heading: 'Візуальний редактор',
      items: [
        { label: 'Вибрати елемент', keys: 'Enter · Пробіл' },
        { label: 'Перемістити елемент на 1%', keys: 'Стрілки' },
        { label: 'Перемістити елемент на 5%', keys: 'Shift + стрілки' },
        { label: 'Видалити власний елемент', keys: 'Delete' },
        { label: 'Вибрати полотно', keys: 'Escape' },
      ],
    },
  ],
  schdkTabsLabel: 'Налаштування ЩДК',
  gameTab: 'Проведення гри',
  editorTab: 'Редагування питань',
  questionText: 'Текст питання',
  sentenceCorrection:
    'Капіталізувати перше слово та додавати крапку, якщо наприкінці немає розділового знака.',
  answers: 'Відповіді',
  answersCorrection:
    'Капіталізувати перше слово основної, альтернативних і неправильних відповідей.',
  answerComment: 'Коментар до відповіді',
  autoFullscreen: 'Автоматично вмикати повноекранний режим',
  autoFullscreenDescription: 'Переходити в повноекранний режим на початку гри.',
  signalVolume: 'Гучність звукових сигналів',
  signalVolumeDescription: 'Головний сигнал і попередження таймера.',
  musicVolume: 'Гучність музики',
  musicVolumeDescription: 'Музика під час пауз між раундами.',
};
