export const visualEditorCopy = {
  uk: {
    labels: {
      logo: 'Лого гри',
      intro: 'Питання №5',
      handout: 'Роздатка',
      question: 'Текст питання',
      timer: 'Таймер',
      answerComment: 'Коментар до відповіді',
      alternativeAnswer: 'Альтернативна відповідь',
      answer: 'Відповідь',
      progress: 'Прогрес',
      controls: 'Кнопки керування',
    },
    previewText: 'Текст питання',
    customText: 'Текст',
    alignments: {
      leftTop: 'Ліворуч угорі',
      centerTop: 'По центру вгорі',
      rightTop: 'Праворуч угорі',
      leftCenter: 'Ліворуч по центру',
      centerCenter: 'По центру',
      rightCenter: 'Праворуч по центру',
      leftBottom: 'Ліворуч унизу',
      centerBottom: 'По центру внизу',
      rightBottom: 'Праворуч унизу',
    },
    customLimit: 'Можна додати не більше 20 власних елементів.',
    imagesTooLarge:
      'Зображення завеликі для збереження. Видаліть одне з них або виберіть менший файл.',
    hiddenSuffix: '. Приховано у грі',
    dragInstruction: 'Перетягніть, щоб змінити позицію',
    textFormatting: 'Оформлення тексту',
    size: 'Розмір',
    color: 'Колір',
    alignLeft: 'Вирівняти ліворуч',
    alignCenter: 'Вирівняти по центру',
    alignRight: 'Вирівняти праворуч',
    alignJustify: 'Вирівняти по ширині',
    bold: 'Напівжирний',
    italic: 'Курсив',
    underline: 'Підкреслення',
    verticalAlignment: 'Вертикальне вирівнювання',
    up: 'Вгору',
    center: 'По центру',
    down: 'Вниз',
    lineHeight: 'Міжрядковий інтервал',
    letterSpacing: 'Міжлітерний інтервал',
    elementStyle: 'Фон і вигляд елемента',
    backgroundColor: 'Колір фону',
    gradient: 'Градієнт',
    gradientColor: 'Другий колір',
    gradientStart: 'Перший колір',
    gradientDirection: 'Напрямок градієнта',
    rounding: 'Заокруглення',
    elementOpacity: 'Прозорість елемента',
    removeElementBackground: 'Прибрати фон елемента',
    imagePosition: 'Позиція зображення',
    alignment: 'Вирівнювання',
    workspaceActions: 'Дії з робочою областю',
    replaceBackground: 'Замінити фон',
    applyImage: 'Застосувати зображення',
    removeBackground: 'Видалити фон',
    backgroundOpacity: 'Прозорість фону',
    canvasGradient: 'Градієнт полотна',
    opacity: 'Прозорість',
    actions: (label: string) => `Дії: ${label}`,
    showInGame: 'Показати у грі',
    hideInGame: 'Приховати у грі',
    ownText: 'Власний текст',
    ownImage: 'Власне зображення',
    editText: 'Змінити текст',
    text: 'Текст',
    replaceImage: 'Замінити зображення',
    removeImage: 'Видалити зображення',
    removeElement: 'Видалити елемент',
    addElement: 'Додати елемент',
    addText: 'Додати редагований текст на екран гри',
    addImage: 'Додати власне зображення або логотип',
    importTemplate: 'Імпортувати шаблон оформлення',
    exportTemplate: 'Експортувати шаблон оформлення',
    chooseImage: 'Оберіть файл зображення.',
    gameLayout: 'Макет екрана гри',
    hidden: 'Приховано',
    undo: 'Скасувати останню зміну',
    redo: 'Повторити скасовану зміну',
  },
  en: {
    labels: {
      logo: 'Game logo',
      intro: 'Question #5',
      handout: 'Handout',
      question: 'Question text',
      timer: 'Timer',
      answerComment: 'Answer comment',
      alternativeAnswer: 'Alternative answer',
      answer: 'Answer',
      progress: 'Progress',
      controls: 'Controls',
    },
    previewText: 'Question text',
    customText: 'Text',
    alignments: {
      leftTop: 'Top left',
      centerTop: 'Top center',
      rightTop: 'Top right',
      leftCenter: 'Center left',
      centerCenter: 'Center',
      rightCenter: 'Center right',
      leftBottom: 'Bottom left',
      centerBottom: 'Bottom center',
      rightBottom: 'Bottom right',
    },
    customLimit: 'You can add up to 20 custom elements.',
    imagesTooLarge:
      'The images are too large to save. Remove one or choose a smaller file.',
    hiddenSuffix: '. Hidden in game',
    dragInstruction: 'Drag to change position',
    textFormatting: 'Text formatting',
    size: 'Size',
    color: 'Color',
    alignLeft: 'Align left',
    alignCenter: 'Align center',
    alignRight: 'Align right',
    alignJustify: 'Justify',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    verticalAlignment: 'Vertical alignment',
    up: 'Up',
    center: 'Center',
    down: 'Down',
    lineHeight: 'Line height',
    letterSpacing: 'Letter spacing',
    elementStyle: 'Element background and appearance',
    backgroundColor: 'Background color',
    gradient: 'Gradient',
    gradientColor: 'Second color',
    gradientStart: 'First color',
    gradientDirection: 'Gradient direction',
    rounding: 'Corner rounding',
    elementOpacity: 'Element opacity',
    removeElementBackground: 'Remove element background',
    imagePosition: 'Image position',
    alignment: 'Alignment',
    workspaceActions: 'Workspace actions',
    replaceBackground: 'Replace background',
    applyImage: 'Apply image',
    removeBackground: 'Remove background',
    backgroundOpacity: 'Background opacity',
    canvasGradient: 'Canvas gradient',
    opacity: 'Opacity',
    actions: (label: string) => `Actions: ${label}`,
    showInGame: 'Show in game',
    hideInGame: 'Hide in game',
    ownText: 'Custom text',
    ownImage: 'Custom image',
    editText: 'Edit text',
    text: 'Text',
    replaceImage: 'Replace image',
    removeImage: 'Remove image',
    removeElement: 'Remove element',
    addElement: 'Add element',
    addText: 'Add editable text to the game screen',
    addImage: 'Add a custom image or logo',
    importTemplate: 'Import layout template',
    exportTemplate: 'Export layout template',
    chooseImage: 'Choose an image file.',
    gameLayout: 'Game screen layout',
    hidden: 'Hidden',
    undo: 'Undo the last change',
    redo: 'Redo the reverted change',
  },
};
