import {
  GOOGLE_DRIVE_SCOPES,
  GoogleDriveAuthorizationError,
  GoogleDriveClient,
  type DriveAccount,
} from './client.js';
import {
  createAIQuestionFilename,
  GLOBAL_AI_QUESTION_ADMIN_EMAILS,
  GLOBAL_AI_QUESTION_FOLDER_ID,
  isGlobalAIQuestionAdmin,
  isDriveAIQuestionName,
  parseDriveAIQuestionFile,
  parseDriveAIQuestionWrite,
  type DriveAIQuestion,
  type DriveAIQuestionFile,
  type DriveAIQuestionStorage,
  type DriveAIQuestionWrite,
  type DriveGlobalAIQuestionStorage,
} from './ai-questions.js';
import {
  createGamePackageFilename,
  isDriveGamePackageName,
  parseDriveGamePackageWrite,
  parseDrivePackageReference,
  toDrivePackageReference,
  type DriveGamePackage,
  type DriveGamePackageFile,
  type DriveGamePackageWrite,
  type DrivePackageStorage,
} from './game-packages.js';
import {
  isDriveFileId,
  parseDriveSettingsDocument,
  type DriveRecentPackage,
  type DriveSettingsDocument,
  type TimedSection,
} from './settings.js';
import {
  createAIQuestionsPackageFilename,
  isDriveAIQuestionsPackageName,
  parseDriveAIQuestionsPackageFile,
  parseDriveAIQuestionsPackageWrite,
  type DriveAIQuestionsPackage,
  type DriveAIQuestionsPackageFile,
  type DriveAIQuestionsPackageStorage,
  type DriveAIQuestionsPackageWrite,
} from './ai-questions-packages.js';
import {
  createQuestionDatabasePackage,
  flattenQuestionDatabase,
  parseQuestionDatabaseDocument,
  type DriveQuestionDatabaseStorage,
  type QuestionDatabaseDocument,
  type QuestionDatabaseEntry,
  type QuestionDatabasePackage,
  type QuestionDatabaseQuestion,
} from './question-database.js';
import {
  DRIVE_DICTIONARY_MIME_TYPE,
  GLOBAL_DICTIONARY_FOLDER_ID,
  SCHDK_DICTIONARY_EXTENSION,
  createDictionaryFilename,
  parseDriveDictionaryWrite,
  type DriveDictionary,
  type DriveDictionaryFile,
  type DriveDictionaryStorage,
  type DriveDictionaryWrite,
} from './dictionaries.js';

export {
  GOOGLE_DRIVE_SCOPES,
  GoogleDriveAuthorizationError,
  GoogleDriveClient,
  type DriveAccount,
  createAIQuestionFilename,
  GLOBAL_AI_QUESTION_ADMIN_EMAILS,
  GLOBAL_AI_QUESTION_FOLDER_ID,
  isGlobalAIQuestionAdmin,
  isDriveAIQuestionName,
  parseDriveAIQuestionFile,
  parseDriveAIQuestionWrite,
  type DriveAIQuestion,
  type DriveAIQuestionFile,
  type DriveAIQuestionStorage,
  type DriveAIQuestionWrite,
  type DriveGlobalAIQuestionStorage,
  createGamePackageFilename,
  isDriveGamePackageName,
  parseDriveGamePackageWrite,
  parseDrivePackageReference,
  toDrivePackageReference,
  type DriveGamePackage,
  type DriveGamePackageFile,
  type DriveGamePackageWrite,
  type DrivePackageStorage,
  isDriveFileId,
  parseDriveSettingsDocument,
  type DriveRecentPackage,
  type DriveSettingsDocument,
  type TimedSection,
  createAIQuestionsPackageFilename,
  isDriveAIQuestionsPackageName,
  parseDriveAIQuestionsPackageFile,
  parseDriveAIQuestionsPackageWrite,
  type DriveAIQuestionsPackage,
  type DriveAIQuestionsPackageFile,
  type DriveAIQuestionsPackageStorage,
  type DriveAIQuestionsPackageWrite,
  createQuestionDatabasePackage,
  flattenQuestionDatabase,
  parseQuestionDatabaseDocument,
  type DriveQuestionDatabaseStorage,
  type QuestionDatabaseDocument,
  type QuestionDatabaseEntry,
  type QuestionDatabasePackage,
  type QuestionDatabaseQuestion,
  DRIVE_DICTIONARY_MIME_TYPE,
  GLOBAL_DICTIONARY_FOLDER_ID,
  SCHDK_DICTIONARY_EXTENSION,
  createDictionaryFilename,
  parseDriveDictionaryWrite,
  type DriveDictionary,
  type DriveDictionaryFile,
  type DriveDictionaryStorage,
  type DriveDictionaryWrite,
};
