import {
  GOOGLE_DRIVE_SCOPES,
  GoogleDriveAuthorizationError,
  GoogleDriveError,
  GoogleDriveClient,
  type DriveAccount,
  type GoogleDriveErrorCode,
} from './services/client/client.js';
import {
  createAIQuestionFilename,
  GLOBAL_AI_QUESTION_ADMIN_EMAILS,
  GLOBAL_AI_QUESTION_FOLDER_ID,
  isGlobalAIQuestionAdmin,
  isDriveAIQuestionName,
  parseDriveAIQuestionFile,
  parseDriveAIQuestionWrite,
  type DriveAIQuestion,
  type DriveAIQuestionFile,
  type DriveAIQuestionStorage,
  type DriveAIQuestionWrite,
  type DriveGlobalAIQuestionStorage,
} from './services/ai-questions/ai-questions.js';
import {
  createGamePackageFilename,
  isDriveGamePackageName,
  parseDriveGamePackageWrite,
  parseDrivePackageReference,
  toDrivePackageReference,
  type DriveGamePackage,
  type DriveGamePackageFile,
  type DriveGamePackageWrite,
  type DrivePackageStorage,
} from './services/game-packages/game-packages.js';
import {
  isDriveFileId,
  type DriveRecentPackage,
  type DriveSettingsDocument,
  type DriveSettingsFile,
  type DriveVisualAssetsDocument,
  type DriveVisualAssetsFile,
  type TimedSection,
  parseDriveVisualAssetsDocument,
} from './services/settings/settings.js';
import { parseDriveSettingsDocument } from './parsers/settings/parse-drive-settings-document.js';
import {
  createAIQuestionsPackageFilename,
  isDriveAIQuestionsPackageName,
  parseDriveAIQuestionsPackageWrite,
  type DriveAIQuestionsPackage,
  type DriveAIQuestionsPackageFile,
  type DriveAIQuestionsPackageStorage,
  type DriveAIQuestionsPackageWrite,
} from './services/ai-question-packages/ai-questions-packages.js';
import { parseDriveAIQuestionsPackageFile } from './parsers/ai-question-packages/parse-drive-ai-questions-package-file.js';
import {
  createQuestionDatabasePackage,
  flattenQuestionDatabase,
  parseQuestionDatabaseDocument,
  type DriveQuestionDatabaseStorage,
  type QuestionDatabaseDocument,
  type QuestionDatabaseEntry,
  type QuestionDatabasePackage,
  type QuestionDatabaseQuestion,
} from './services/question-database/question-database.js';
import {
  DRIVE_DICTIONARY_MIME_TYPE,
  GLOBAL_DICTIONARY_FOLDER_ID,
  SCHDK_DICTIONARY_EXTENSION,
  createDictionaryFilename,
  parseDriveDictionaryWrite,
  type DriveDictionary,
  type DriveDictionaryFile,
  type DriveDictionaryStorage,
  type DriveDictionaryWrite,
} from './services/dictionaries/dictionaries.js';

export {
  GOOGLE_DRIVE_SCOPES,
  GoogleDriveAuthorizationError,
  GoogleDriveError,
  GoogleDriveClient,
  type DriveAccount,
  type GoogleDriveErrorCode,
  createAIQuestionFilename,
  GLOBAL_AI_QUESTION_ADMIN_EMAILS,
  GLOBAL_AI_QUESTION_FOLDER_ID,
  isGlobalAIQuestionAdmin,
  isDriveAIQuestionName,
  parseDriveAIQuestionFile,
  parseDriveAIQuestionWrite,
  type DriveAIQuestion,
  type DriveAIQuestionFile,
  type DriveAIQuestionStorage,
  type DriveAIQuestionWrite,
  type DriveGlobalAIQuestionStorage,
  createGamePackageFilename,
  isDriveGamePackageName,
  parseDriveGamePackageWrite,
  parseDrivePackageReference,
  toDrivePackageReference,
  type DriveGamePackage,
  type DriveGamePackageFile,
  type DriveGamePackageWrite,
  type DrivePackageStorage,
  isDriveFileId,
  parseDriveSettingsDocument,
  type DriveRecentPackage,
  type DriveSettingsDocument,
  type DriveSettingsFile,
  type DriveVisualAssetsDocument,
  type DriveVisualAssetsFile,
  type TimedSection,
  parseDriveVisualAssetsDocument,
  createAIQuestionsPackageFilename,
  isDriveAIQuestionsPackageName,
  parseDriveAIQuestionsPackageFile,
  parseDriveAIQuestionsPackageWrite,
  type DriveAIQuestionsPackage,
  type DriveAIQuestionsPackageFile,
  type DriveAIQuestionsPackageStorage,
  type DriveAIQuestionsPackageWrite,
  createQuestionDatabasePackage,
  flattenQuestionDatabase,
  parseQuestionDatabaseDocument,
  type DriveQuestionDatabaseStorage,
  type QuestionDatabaseDocument,
  type QuestionDatabaseEntry,
  type QuestionDatabasePackage,
  type QuestionDatabaseQuestion,
  DRIVE_DICTIONARY_MIME_TYPE,
  GLOBAL_DICTIONARY_FOLDER_ID,
  SCHDK_DICTIONARY_EXTENSION,
  createDictionaryFilename,
  parseDriveDictionaryWrite,
  type DriveDictionary,
  type DriveDictionaryFile,
  type DriveDictionaryStorage,
  type DriveDictionaryWrite,
};
